server:
port: 8080


spring:

datasource:
username: "postgres"
password: "postgres"
url: "jdbc:postgresql://localhost:5432/industry_master"
driverClassName: "org.postgresql.Driver"
hikari:
connection-timeout: 50000
maximum-pool-size: 20
jpa:
show-sql: true
hibernate:
  ddl-auto: validate
  properties:
    hibernate:
      format-sql: true
      jdbc:
        lob.non_contextual_creation: true
dialect: org.hibernate.dialect.PostgreSQL10Dialect